version: '3.4'
services:
  db:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db